# baseurl: '/'  # only use if different from '/'
permalink: pretty
title: Haus des Physio

credits:
  webdesign: "website by martin-j"
  legal: "© Haus des Physio"

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.jpg"
  desktop_height: "32px"
  desktop_width: "120px"

home:
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
    permalink: /about/team/:name/
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - licences/
  - README.md
  - builtatlightspeed.json
  - netlify.toml
