baseurl: '/'
destination: _site
permalink: pretty
title: Main Vital
description: Willkommen bei Main Vital, Ihrer modernen Physiotherapiepraxis in Hallstadt-Dörfleins bei Bamberg. Für ganzheitliche Gesundheit und mehr Lebensqualität.

credits:
  webdesign: "website by m-martin-j"
  legal:

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"

home:
  limit_services: 3

cookies:
  expiry_days: 31

announcements:
  start_offset_days_modal_announcement_vacation: 14
  min_days_vacation_auto_announcement: 3

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
    permalink: /about/team/:name/
  pages:
    output: true
  downloads:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
      description: Unser Leistungsspektrum umfasst Manuelle Therapie, Krankengymnastik, Lymphdrainage, Massagen, sowie weitere Therapieformen, individuell auf Sie abgestimmt.
      show_call_button: true
      call_button_text: Termin vereinbaren
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - custom_cert/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - licenses/
  - README.md
  - builtatlightspeed.json
  - netlify.toml
