baseurl: '/'
destination: _site
permalink: pretty
title: Main Vital

credits:
  webdesign: "website by m-martin-j"
  legal:

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"

home:
  limit_services: 3

cookies:
  expiry_days: 31
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: false
    permalink: /about/team/:name/
  pages:
    output: true
  downloads:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - custom_cert/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - licenses/
  - README.md
  - builtatlightspeed.json
  - netlify.toml
