name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ARTIFACT_DIR: _site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure Bundler
      run: bundle config set --local path vendor/bundle
    - name: Install dependencies
      run: bundle install
    - name: Build
      run: bundle exec jekyll build  # --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ${{ env.ARTIFACT_DIR }}
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: site
        path: ${{ env.ARTIFACT_DIR }}
    - name: Deploy to target
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        key: ${{ secrets.DEPLOY_KEY }}
        target: ${{ secrets.DEPLOY_TARGET_DIR }}
        source: ${{ env.ARTIFACT_DIR }}/*
        rm: true
        strip_components: 1
    environment:
      name: deploy-target
      # url: ${{ secrets.DEPLOY_URL }}
