name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: bundle install --path vendor/bundle
    - name: Setup Pages
      uses: actions/configure-pages@v5
    # - name: Build
    #   uses: actions/jekyll-build-pages@v1
    - name: Build
      run: bundle exec jekyll build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
